import std/[macros, compilesettings, os, strformat, strutils]

func encodeCBORPluginMetaCxxArray(iid, className, uri: string): string {.compiletime.} =
  ## TODO replace with https://github.com/vacp2p/nim-cbor-serialization/
  ## Based on https://github.com/qt/qtbase/blob/6.10.2/src/tools/moc/generator.cpp#L1425
  ## Basic plugin metadata encoder. Returns the C++ unsigned char array representation
  ## of the CBOR-encoded plugin metadata.
  const indent = "    "
  proc cborStringHeader(len: int): string =
    if len <= 23:
      result = "0x" & (0x60 + len).toHex(2) & ", "
    else:
      result = "0x78, 0x" & len.toHex(2) & ", "

  proc appendAscii(s: string, res: var string) =
    for i, c in s:
      res.add("'" & c & "', ")
      if (i + 1) mod 8 == 0 and i < s.high:
        res.add("\n" & indent)
    res.add("\n")

  proc appendComment(s: string, res: var string) =
    res.add(indent & "// \"" & s & "\"\n")

  var res = indent & "0xBF," & "\n"
  # IID
  appendComment("IID", res)
  res.add(indent & "0x02, ") # QtPluginMetaDataKeys::IID = 0x02
  res.add(cborStringHeader(iid.len) & "\n" & indent)
  appendAscii(iid, res)

  # className
  appendComment("className", res)
  res.add(indent & "0x03, ") # QtPluginMetaDataKeys::ClassName = 0x03
  res.add(cborStringHeader(className.len) & "\n" & indent)
  appendAscii(className, res)

  # "uri"
  appendComment("uri", res)
  res.add(indent & "0x63, 'u', 'r', 'i',\n" & indent & "0x81,\n" & indent)
  res.add(cborStringHeader(uri.len) & "\n" & indent)
  appendAscii(uri, res)
  res.add("\n" & indent & "0xff,\n")

  res

func generateCppMetadataHandlerCode(
    iid, className, uri: string
): string {.compiletime.} =
  # Qt plugins place metadata in a specially named section accessed using
  # __attribute__((section)) or equivalent - since we don't have that in nim
  # (yet), we'll generate a small C++ file as part of compilation that can do
  # this for us:
  # https://github.com/qt/qtbase/blob/6.10.2/src/corelib/plugin/qplugin.h#L127
  #
  # The metadata itself is usually generated by `moc` but we can do so on the
  # fly within the macro:
  &"""
#include <QtCore/qplugin.h>

static constexpr unsigned char qt_pluginMetaData[] = {{
   {encodeCBORPluginMetaCxxArray(iid, className, uri)}
}};

extern "C" Q_DECL_EXPORT QT_PREPEND_NAMESPACE(QPluginMetaData) qt_plugin_query_metadata_v2()
{{
    static constexpr QT_PLUGIN_METADATAV2_SECTION QPluginMetaDataV2<qt_pluginMetaData> md{{}};
    return md;
}}

"""

func generateQmldirContent(moduleName, libName: string): string {.compiletime.} =
  "module " & moduleName & "\n" & "plugin " & libName

const pluginDir = querySetting(SingleValueSetting.outDir)
const nimcacheDir = querySetting(SingleValueSetting.nimcacheDir)

const pluginRegistrationCppFile = nimcacheDir / "pluginRegistration.cpp"

proc qpluginImpl(T, U: NimNode, iid, uri, cflags: string): NimNode {.compiletime.} =
  let typename = $T

  createDir(nimcacheDir)
  writeFile(
    pluginRegistrationCppFile, generateCppMetadataHandlerCode(iid, typename, uri)
  )

  quote:
    {.compile(pluginRegistrationCppFile, `cflags`).}

    let pluginSingleton = `T`()
    `U`.create(pluginSingleton)

    proc qt_plugin_instance(): pointer {.exportc, dynlib, cdecl.} =
      return pluginSingleton.h

macro Q_PLUGIN_METADATA*(T, U: typed, iid, uri, cflags: static string): untyped =
  ## https://doc.qt.io/qt-6/qtplugin.html#Q_PLUGIN_METADATA
  ##
  ## Loosely translated, will likely change in the future..
  ##
  ## Called like so:
  ## Q_PLUGIN_METADATA(MyPlugin, QObject, "someiid", "http://myuri", QtCoreCFlags)
  qpluginImpl(T, U, iid, uri, cflags)

const qmldirPath = pluginDir / "qmldir"
const projectName = querySetting(SingleValueSetting.projectName)

macro QML_PLUGIN_METADATA*(
    T, U: typed, moduleName, iid, uri, cflags: static string
): untyped =
  ## Version of Q_PLUGIN_METADATA that also creates a `qmldir` file
  ## Called like so:
  ## QML_PLUGIN_METADATA(MyPlugin, QQmlPluginExtension, "MyPlugin", "someiid", "http://myuri", QtQmlCFlags)

  writeFile(qmldirPath, generateQmldirContent(moduleName, projectName))
  qpluginImpl(T, U, iid, uri, cflags)
